---
image:
  registry: "<container_image_registry_hostname>"

storage:
  host: "<postgresql_server_hostname>"

bootstrap:
  enabled: true

console:
  enabled: true

certManager:
  issuerGroup: certmanager.step.sm
  issuerKind: StepClusterIssuer

common:
  tls:
    public:
      enabled: true
      certManager:
        issuerName: canton-tls-issuer
    admin:
      enabled: true
      certManager:
        issuerName: canton-tls-issuer
  mtls:
    admin:
      enabled: false

manager:
  storage:
    database: "mydomain"
    user: "mydomain"
    existingSecret:
      name: "mydomain-postgresql"
      key: "mydomain"

mediator:
  storage:
    database: "mymediator"
    user: "mymediator"
    existingSecret:
      name: "mymediator-postgresql"
      key: "mymediator"

sequencer:
  storage:
    database: "mysequencer"
    user: "mysequencer"
    existingSecret:
      name: "mysequencer-postgresql"
      key: "mysequencer"

testing:
  bootstrap:
    remoteParticipants:
      - name: "participant1"
        host: "participant1-canton-participant.canton.svc.cluster.local"
        tls:
          admin:
            enabled: true
            certManager:
              issuerName: canton-tls-issuer
            ca: "/tls-participant1/ca.crt"
        mtls:
          admin:
            enabled: false
