---
image:
  registry: "<container_image_registry_hostname>"

storage:
  host: "<postgresql_server_hostname>"
  database: "myjson"
  user: "myjson"
  existingSecret:
    name: "myjson-postgresql"
    key: "myjson"

ledgerAPI:
  host: "participant1-canton-participant.canton.svc.cluster.local"

certManager:
  issuerGroup: certmanager.step.sm
  issuerKind: StepClusterIssuer

tls:
  enabled: true
  certManager:
    issuerName: canton-tls-issuer
mtls:
  enabled: false
